---
thema: Thema der Arbeit
schlagworte: Spezifische, Schlagworte, zur, Ausarbeitung
zusammenfassung: Lorem Ipsum
autor: Max Mustermann
ausgabedatum: 07.03.2022
abgabedatum: 07.05.2022
autorStrasse: Buchenstraße 7
autorPLZ: 99999 
autorOrt:  Flensburg
autorGeburtsort: Tettnang
autorGeburtsdatum: 01.01.1990
prueferA: Boris Dudelsack 
prueferB: Jan Christiansen
firma: -
fakultaet: Medieninformatik
studiengang: Programmierung


lang: de
bib: true
# table of contents
toc: true 
# list of figures
lof: true
# list of tables
lot: true
documentclass: report
pagenumberstyle_before: Roman
pagenumberstyle_thesis: arabic
mainfont: abc
fontsize: 12pt
geometry: margin=3cm,headsep=.5cm,headheight=.5cm
papersize: a4paper
fontfamily: libertine

# color of reference links and online urls, uncomment if u want them to be black, or change to any color u want
# linkcolor: black 
# urlcolor: black

# References as link to the corresponding entry in the bibliography
# link-citations: true
---

